# permissions for end users to edit clusterwatchnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterwatchnamespace-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clustermanager
    app.kubernetes.io/part-of: clustermanager
    app.kubernetes.io/managed-by: kustomize
  name: clusterwatchnamespace-editor-role
rules:
- apiGroups:
  - cluster.cdx.foc
  resources:
  - clusterwatchnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.cdx.foc
  resources:
  - clusterwatchnamespaces/status
  verbs:
  - get
