# permissions for end users to view clusterwatchnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterwatchnamespace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clustermanager
    app.kubernetes.io/part-of: clustermanager
    app.kubernetes.io/managed-by: kustomize
  name: clusterwatchnamespace-viewer-role
rules:
- apiGroups:
  - cluster.cdx.foc
  resources:
  - clusterwatchnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.cdx.foc
  resources:
  - clusterwatchnamespaces/status
  verbs:
  - get
